openapi: 3.0.3
info:
  title:  API fornite dal normalizzatore - servizio di deduplica
  version: 1.0.0
paths:
  /send-normalizzatore-ingress/v1/normalizzazione:
    post:
      operationId: normalizzazione
      summary: PN richiede la normalizzazione batch
      description: >- 
          Il file in ingresso conterrà i seguenti campi gestiti con logica posizionale (nessuna intestazione, separatore ';'):
            - IdCodiceCliente : Id del cliente
            - Provincia : Sigla Provincia - opzionale
            - Cap : cap - opzionale
            - localita : località/comune - obbligatorio
            - localitaAggiuntiva : frazione - opzionale
            - indirizzo : svia - obbligatorio - contiene la via completa DUG + TOPONIMO + CIVICO
            - indirizzoAggiuntivo : edificio - opzionale
            - stato : sstato - opzionale
          Il processo di normalizzazione creerà un file di output contenente i seguenti campi gestiti con logica posizionale (nessuna intestazione, separatore ';'):
            - IDCODICECLIENTE : Id del cliente;
            - NRISULTATONORM : Risultato di normalizzazione (0 : scartato/ 1,2,3,4,5 : normalizzato);
            - FPOSTALIZZABILE (0 : NON Postalizzabile, 1 : Postalizzabile);
            - NERRORENORM : Codice di errore;
            - SSIGLAPROV : Sigla provincia normalizzata;
            - SSTATOUFF : Stato normalizzato (Valorizzato ITALIA, REPUBBLICA DI SAN MARINO e CITTA' DEL VATICANO + TUTTI GLI STATI ESTERI);
            - SSTATOABB : Stato abbreviato normalizzato;
            - SSTATOSPEDIZIONE : Stato di Spedizione;
            - SCOMUNEUFF : Comune normalizzato;
            - SCOMUNEABB : Comune Abbreviato normalizzato;
            - SCOMUNESPEDIZIONE : Comune di spedizione;
            - SFRAZIONEUFF : Frazione normalizzata;
            - SFRAZIONEABB : Frazione Abbreviata normalizzata;
            - SFRAZIONESPEDIZIONE : Frazione di Spedizione;
            - SCIVICOALTRO : altri elementi del civico (interno, piano, scala, palazzo …) - VA IN INDIRIZZO 2
            - SCAP : cap normalizzato;
            - SPRESSO : informazioni di presso e casella postale (C.P 123, Presso sig. rossi …) -  VA IN NAME 2;
            - SVIACOMPLETAUFF : via completa normalizzata (DUG+COMPL+TOPONIMO+CIVICO POSTALE) ;
            - SVIACOMPLETAABB: via completa normalizzata abbreviata (DUG+COMPL+TOPONIMO+CIVICO POSTALE ABBREVIATA) ;
            - SVIACOMPLETASPEDIZIONE : Indirizzo di Stampa;

            NERRORENORM può contenere i seguenti valori
              - //FIXME: aggiungere codifica errori

      parameters:
        - $ref: '#/components/parameters/xPagopaAddrManCxId'
        - $ref: '#/components/parameters/xPagopaAddrManApiKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NormalizzazioneRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalizzazioneResponse'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  /send-normalizzatore-ingress/v1/deduplica:
    post:
      operationId: deduplica
      summary: PN richiede la deduplica online
      parameters:
        - $ref: '#/components/parameters/xPagopaAddrManCxId'
        - $ref: '#/components/parameters/xPagopaAddrManApiKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeduplicaRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeduplicaResponse'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

components:


  parameters:
    xPagopaAddrManCxId:
      name: "pn-address-manager-cx-id"
      in: header
      schema:
        type: string
      required: true
    xPagopaAddrManApiKey:
      name: x-api-key
      description: Credenziale di accesso
      in: header
      required: true
      schema:
        type: string
        x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL


  schemas:

    NormalizzazioneRequest:
      type: object
      required:
        - requestId
        - sha256
        - uri
      properties:
        requestId:
          type: string
          minLength: 1
          maxLength: 250
          description: id lavorazione
        uri:
          type: string
          minLength: 5
          maxLength: 2000
          description: Le coordinate del documento correlato allo stato.
        sha256:
          type: string
          minLength: 40
          maxLength: 50
          description: sha256, codificato in base 64, del contenuto del file riferenziato dal campo uri
        idConf:
          type: string
          description: Eventuale configurazione speciale per la normalizzazione

    NormalizzazioneResponse:
      type: object
      required:
        - requestId
      description: >-
        error valorizzato solo in caso di mancata accettazione
      properties:
        requestId:
          type: string
          minLength: 1
          maxLength: 250
          description: id lavorazione
        error:
          type: string
          description: >-
            identificativo dell'errore            
              - NOR400: BAD REQUEST. Mi passa un input errato sia dal punto di vista del contenuto o formale;
              - NOR401: UNAUTHORIZATED. Mi passa delle credenziali vuote o errate;
              - NOR404: NOT FOUND. Il servizio nel server Postel non è disponibile;
              - NOR500: INTERNAL_SERVER_ERROR. Il servizio nei server Postel non è raggiungibile;
              - NOR998: SERVIZIO DI NORMALIZZAZIONE NON DISPONIBILE; 

    DeduplicaRequest:
      type: object
      required:
        - masterIn
        - slaveIn
      properties:
        configIn:
          $ref: '#/components/schemas/ConfigIn'
        masterIn:
          description: Indirizzo base con cui deduplicare lo slave
          $ref: '#/components/schemas/AddressIn'
        slaveIn:
          description: Indirizzo oggetto della deduplica
          $ref: '#/components/schemas/AddressIn'

    ConfigIn:
      type: object
      properties:
        configurazioneDeduplica:
          type: string
        configurazioneNorm:
          type: string

    AddressIn:
      type: object
      required:
        - localita
        - indirizzo
      properties:
        id:
          type: string
        provincia:
          type: string
        cap:
          type: string
        localita:
          type: string
        localitaAggiuntiva:
          type: string
        indirizzo:
          type: string
        indirizzoAggiuntivo:
          type: string
        stato:
          type: string

    DeduplicaResponse:
      type: object
      description: >-
        slaveOut e risultatoDedu: obbligatori in caso di risposta di successo
        errore: valorizzato in caso di risposta con errore
      properties:
        masterOut:
          description: risultato delle deduplica
          $ref: '#/components/schemas/AddressOut'
        slaveOut:
          description: risultato delle deduplica
          $ref: '#/components/schemas/AddressOut'
        risultatoDedu:
          type: boolean
          description: >-
            Codice contenete l'esito del processo di deduplica
            - false: Indirzzi differenti
            - true: Indirizzi uguali
        errore:
          type: string
          description: >-
            identificativo dell'errore
            - DED400: BAD REQUEST. Mi passa un input errato sia dal punto di vista del contenuto o formale;
            - DED401: UNAUTHORIZATED. Mi passa delle credenziali vuote o errate;
            - DED404: NOT FOUND. Il servizio nel server Postel non è disponibile;
            - DED500: INTERNAL_SERVER_ERROR. Il servizio nei server Postel non è raggiungibile; 
            - DED998: SERVIZIO DI NORMALIZZAZIONE NON DISPONIBILE; 
            - DED997: SERVIZIO ORACLE NON DISPONIBILE; 
            - DED992: ERRORE_GENERICO;
            - DED996: ENTRAMBI_SCARTATI;
            - DED995: INDIRIZZO_MASTER_SCARTATO;
            - DED994: INDIRIZZO_SLAVE_SCARTATO;

    AddressOut:
      type: object
      required:
        - nRisultatoNorm
        - fPostalizzabile
      properties:
        id:
          type: string
        nRisultatoNorm:
          type: integer
        nErroreNorm:
          type: integer
        sSiglaProv:
          type: string
        fPostalizzabile:
          type: string
        sStatoUff:
          type: string
        sStatoAbb:
          type: string
        sStatoSpedizione:
          type: string
        sComuneUff:
          type: string
        sComuneAbb:
          type: string
        sComuneSpedizione:
          type: string
        sFrazioneUff:
          type: string
        sFrazioneAbb:
          type: string
        sFrazioneSpedizione:
          type: string
        sCivicoAltro:
          type: string
        sCap:
          type: string
        sPresso:
          type: string
        sViaCompletaUff:
          type: string
        sViaCompletaAbb:
          type: string
        sViaCompletaSpedizione:
          type: string

    Problem:
      required:
        - type
        - status
        - title
        - errors
      properties:
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          type: integer
          format: int32
          example: 503
          maximum: 600
          minimum: 100
          exclusiveMaximum: true
        title:
          description: A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: ^[ -~]{0,64}$
          type: string
        detail:
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: ^.{0,1024}$
          type: string
        traceId:
          description: Internal support identifier associated to error
          example: 123e4567-e89b-12d3-a456-426614174000
          type: string
        errors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ProblemError'

    ProblemError:
      required:
        - code
      properties:
        code:
          description: Internal code of the error, in human-readable format
          example: PN_PARAMETER_TOO_LONG | PN_PARAMETER_TOO_SHORT | PN_DUPLICATE_ENTRY | etc...
          type: string
        element:
          description: Parameter or request body field name for validation error
          example: 'body.order.item[2].quantity'
          type: string
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
          maxLength: 1024
          type: string
