spring:
  application:
    name: pn-external-channels

server:
  port: 8082

logging:
  config: classpath:logback.xml


job:
  cron-expression: "*/2 * * * * *" # OGNI 5 SECONDO
#  batch-size: 10
#  messages-csv-template-id: 8
#  results-csv-template-id: 4
#  customer: 8585
#  macroservice:
#    digital: 5066
#    physical: 5065
#
#emailSender:
#  content-type: HTML
#  protocol: smtp
#  host: smtp.gmail.com
#  port: 587
