AWSTemplateFormatVersion: 2010-09-09
Description: Deploy PN-external-channel and ensure infrastructure
Parameters:
  EnvName:
    Type: String
    Description: Nome dell'ambiente destinazione
  EnvNumber:
    Type: String
    Description: Second byte from the left for VPC CIDR
  KeyspaceName:
    Type: String
    Description: cassandra keyspace name
  SendCronExpression:
    Type: String
    Description: Espressione quartz per schedulare gli invii
  InputBucketName:
    Type: String
    Description: Nome del bucket di input dai sistemi di poste
  InputBucketArn:
    Type: String
    Description: Arn del bucket di input dai sistemi di poste
  OutputBucketName:
    Type: String
    Description: Nome del bucket di output verso i sistemi di poste
  OutputBucketArn:
    Type: String
    Description: Arn del bucket di output verso i sistemi di poste

Resources:

  Keyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: !Ref KeyspaceName

  QueuedMessageTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: queued_message
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: id
          ColumnType: text
      RegularColumns:
        - ColumnName: actcode
          ColumnType: text
        - ColumnName: eventstatus
          ColumnType: text
        - ColumnName: eventid
          ColumnType: text
        - ColumnName: iun
          ColumnType: text
        - ColumnName: address
          ColumnType: text
        - ColumnName: addressdetails
          ColumnType: text
        - ColumnName: at
          ColumnType: text
        - ColumnName: attachmentkeys
          ColumnType: list<text>
        - ColumnName: communicationtype
          ColumnType: text
        - ColumnName: municipality
          ColumnType: text
        - ColumnName: pecaddress
          ColumnType: text
        - ColumnName: printmodel
          ColumnType: text
        - ColumnName: province
          ColumnType: text
        - ColumnName: recipientdenomination
          ColumnType: text
        - ColumnName: recipienttaxid
          ColumnType: text
        - ColumnName: requestcorrelationid
          ColumnType: text
        - ColumnName: senderdenomination
          ColumnType: text
        - ColumnName: senderid
          ColumnType: text
        - ColumnName: senderpecaddress
          ColumnType: text
        - ColumnName: servicelevel
          ColumnType: text
        - ColumnName: template
          ColumnType: text
        - ColumnName: zip
          ColumnType: text

  DiscartedMessageTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: discarded_message
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: id
          ColumnType: text
      RegularColumns:
        - ColumnName: message
          ColumnType: text
        - ColumnName: reasons
          ColumnType: list<text>

  CsvTemplateTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: csv_template
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: id
          ColumnType: text
      RegularColumns:
        - ColumnName: columns
          ColumnType: text
        - ColumnName: description
          ColumnType: text
        - ColumnName: idcsv
          ColumnType: text

  ResultDescriptorTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: result_descriptor
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: code
          ColumnType: text
      RegularColumns:
        - ColumnName: positive
          ColumnType: boolean
        - ColumnName: retryable
          ColumnType: boolean
        - ColumnName: servicecode
          ColumnType: text

  SenderCfgByDenominationTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: sender_config_by_denomination
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: denomination
          ColumnType: text
        - ColumnName: channel
          ColumnType: text
        - ColumnName: servicelevel
          ColumnType: text
      RegularColumns:
        - ColumnName: printmodel
          ColumnType: text
        - ColumnName: template
          ColumnType: text

  SenderPecByDenominationTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: sender_pec_by_denomination
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: denomination
          ColumnType: text
      RegularColumns:
        - ColumnName: idpec
          ColumnType: text
        - ColumnName: pec
          ColumnType: text

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref EnvName, ExtChannelCluster]]
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    # Makes sure the log group is created before it is used.
    DependsOn: LogGroup
    Properties:
      # Name of the task definition. Subsequent versions of the task definition are grouped together under this name.
      Family: !Join ['', [!Ref EnvName, ExtChannelTaskDefinition]]
      # awsvpc is required for Fargate
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
      # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
      # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
      # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
      # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
      Cpu: 1024
      # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
      # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
      # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
      # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
      # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
      Memory: 2GB
      # A role needed by ECS.
      # "The ARN of the task execution role that containers in this task can assume. All containers in this task are granted the permissions that are specified in this role."
      # "There is an optional task execution IAM role that you can specify with Fargate to allow your Fargate tasks to make API calls to Amazon ECR."
      ExecutionRoleArn: !Ref ExecutionRole
      # "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that grants containers in the task permission to call AWS APIs on your behalf."
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Sub '${EnvName}-extchannel'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvName}-pn-external-channels:latest'
          Environment:
            - Name: SPRING_DATA_CASSANDRA_KEYSPACENAME
              Value: !Sub ${Keyspace}
            - Name: SPRING_DATA_CASSANDRA_SSL
              Value: true
            - Name: SPRING_DATA_CASSANDRA_CONTACTPOINTS
              Value: !Sub 'cassandra.${AWS::Region}.${AWS::URLSuffix}:9142'
            - Name: DEVOPTIONS_FAKEPNEXTCHNSERVICE
              Value: "true"
            - Name: JOB_CRONEXPRESSION
              Value: !Ref SendCronExpression
            - Name: SPRING_CLOUD_STREAM_BINDINGS_PNEXTCHNNOTIFPECINBOUND_DESTINATION
              Value: !ImportValue { "Fn::Sub": '${EnvName}-extchannel-input-queue-name' }
            - Name: SPRING_CLOUD_STREAM_BINDINGS_PNEXTCHNELABRESULT_DESTINATION
              Value: !ImportValue { "Fn::Sub": '${EnvName}-extchannel-elabres-queue-name' }
            - Name: SPRING_CLOUD_STREAM_BINDINGS_PNEXTCHNSTATUS_DESTINATION
              Value: !ImportValue { "Fn::Sub": '${EnvName}-extchannel-output-queue-name' }
            - Name: S3_BUCKETS_EXTERNALCHANNELSOUT
              Value: !Ref OutputBucketName
            - Name: S3_BUCKETS_EXTERNALCHANNELSIN
              Value: !Ref InputBucketName
            - Name: CLOUD_AWS_REGION_STATIC
              Value: !Ref AWS::Region
            - Name: AWS_REGIONCODE
              Value: !Ref AWS::Region
            - Name: PECBYSMTP_USER
              Value: '{{resolve:secretsmanager:pec_server_credentials_iomsges:SecretString:user}}'
            - Name: PECBYSMTP_PASSWORD
              Value: '{{resolve:secretsmanager:pec_server_credentials_iomsges:SecretString:password}}'
            - Name: PECBYSMTP_IMAPSHOST
              Value: '{{resolve:secretsmanager:pec_server_credentials_iomsges:SecretString:imaps-host}}'
            - Name: PECBYSMTP_SMTPSHOST
              Value: '{{resolve:secretsmanager:pec_server_credentials_iomsges:SecretString:smtps-host}}'
            - Name: PECBYSMTP_SMTPSFOLDER
              Value: '{{resolve:secretsmanager:pec_server_credentials_iomsges:SecretString:smtps-folder}}'
            - Name: EMAILSENDER_USERNAME
              Value: '{{resolve:secretsmanager:email_server_credentials:SecretString:email_user}}'
            - Name: EMAILSENDER_PASSWORD
              Value: '{{resolve:secretsmanager:email_server_credentials:SecretString:email_pwd}}'
          PortMappings:
            - ContainerPort: 8080
          # Send logs to CloudWatch Logs
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  # A role needed by ECS
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref EnvName, ExtChannelExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
  # A role for the containers
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref EnvName, ExtChannelTaskRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
  InstancePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${EnvName}-inst-delpush-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:DescribeRepositories
              - ecr:GetDownloadUrlForLayer
              - sqs:ChangeMessageVisibility
              - sqs:ChangeMessageVisibilityBatch
              - sqs:DeleteMessage
              - sqs:DeleteMessageBatch
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
              - sqs:SendMessageBatch
            Resource:
              - !ImportValue { "Fn::Sub": '${EnvName}-extchannel-input-queue-arn' }
              - !ImportValue { "Fn::Sub": '${EnvName}-extchannel-output-queue-arn' }
              - !ImportValue { "Fn::Sub": '${EnvName}-extchannel-elabres-queue-arn' }
          - Effect: Allow
            Action:
              - cassandra:Modify
              - cassandra:Select
            Resource:
              - !Sub "arn:aws:cassandra:*:${AWS::AccountId}:/keyspace/*/table/*"
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:DeleteObject
              - s3:DeleteObjectVersion
              - s3:GetObjectAcl
              - s3:GetObjectLegalHold
              - s3:GetObjectRetention
              - s3:GetObjectTagging
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
              - s3:GetObjectVersionTagging
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Resource:
              - !Join
                - '/'
                - - !Sub '${InputBucketArn}'
                  - '*'
              - !Join
                - '/'
                - - !Sub '${OutputBucketArn}'
                  - '*'
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Sub '${InputBucketArn}'
              - !Sub '${OutputBucketArn}'
      Roles:
        - !Ref TaskRole
  # A role needed for auto scaling
  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref EnvName, ExtChannelAutoScalingRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole'
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref EnvName, ExtChannelContSecGrp]]
      VpcId: !ImportValue
        "Fn::Sub": '${EnvName}-vpc-id'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
          #SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref EnvName, ExtChannelLbSecGrp]]
      VpcId: !ImportValue
        "Fn::Sub": '${EnvName}-vpc-id'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  ExtChannelService:
    Type: AWS::ECS::Service
    # This dependency is needed so that the load balancer is setup correctly in time
    #DependsOn:
    #  - ListenerHTTP
    Properties:
      #ServiceName: !Sub '${EnvName}-extchannel'
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      # This may need to be adjusted if the container takes a while to start up
      #HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      PlatformVersion: 1.3.0
      NetworkConfiguration:
        AwsvpcConfiguration:
          # change to DISABLED if you're using private subnets that have access to a NAT gateway
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue { "Fn::Sub": '${EnvName}-subnet1' }
            - !ImportValue { "Fn::Sub": '${EnvName}-subnet2' }
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Sub '${EnvName}-extchannel'
          ContainerPort: 8080
          TargetGroupArn: !Ref ExtChaTargetGroup
        - ContainerName: !Sub '${EnvName}-extchannel'
          ContainerPort: 8080
          TargetGroupArn: !Ref ExtChaNetTargetGroup
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref EnvName, ExtChannel]]
      RetentionInDays: 3
  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 1
      ResourceId: !Join ['/', [service, !Ref Cluster, !GetAtt ExtChannelService.Name]]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      # "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that allows Application Auto Scaling to modify your scalable target."
      RoleARN: !GetAtt AutoScalingRole.Arn
  AutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Join ['', [!Ref EnvName, DelPushAutoScalingPolicy]]
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        # Keep things at or lower than 50% CPU utilization, for example
        TargetValue: 60

  ExtChaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      Protocol: HTTP
      Port: 8080
      #HealthCheckEnabled: true
      #HealthCheckIntervalSeconds: 10
      #HealthCheckPath: /
      #HealthCheckPort: 8080
      #HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: 404
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 # default is 300
      VpcId: !ImportValue
        "Fn::Sub": '${EnvName}-vpc-id'

  ExtChaLoadBalancerListner:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !ImportValue
        "Fn::Sub": '${EnvName}-extcha-alb-id'
      Protocol: HTTP
      Port: 8080
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ExtChaTargetGroup
          Order: 1

  ExtChaNetTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      Protocol: TCP
      Port: 8080
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 # default is 300
      VpcId: !ImportValue
        "Fn::Sub": '${EnvName}-vpc-id'

  ExtChaNetLoadBalancerListner:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !ImportValue
        "Fn::Sub": '${EnvName}-extcha-nlb-id'
      Protocol: TCP
      Port: 8080
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ExtChaNetTargetGroup
          Order: 1

Outputs:
  CluserArn:
    Description: ARN del cluster fargate
    Value: !Sub '${Cluster.Arn}'
  ServiceName:
    Description: Nome del servizio di cui fare deploy
    Value: !Sub '${ExtChannelService.Name}'
