AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

Conditions:
  Never: !Equals [ 'true', 'false' ]

# dummy (null) resource, never created
Resources:
  # NotificationProgress DynamoDB Table for mock
  NotificationProgressTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-ExtChannels'
      AttributeDefinitions:
        - AttributeName: "iun"
          AttributeType: "S"
        - AttributeName: "destinationAddress"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun"
          KeyType: "HASH"
        - AttributeName: "destinationAddress"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Internal queues
  InternalQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-external_channels_internal'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1
  
  VerificationCodeTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-VerificationCode2'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  NotificationProgressDynamoTableName:
    Description: Name of dynamodb table containing Notification Progress for mock
    Value: !Ref NotificationProgressTable
  NotificationProgressDynamoTableArn:
    Description: ARN of dynamodb table containing Notification Progress for mock
    Value: !Sub '${NotificationProgressTable.Arn}'
  VerificationCodeTableDynamoTableName:
    Description: Name of dynamodb table containing verification code for mock
    Value: !Ref VerificationCodeTable
  VerificationCodeTableDynamoTableArn:
    Description: ARN of dynamodb table containing verification code for mock
    Value: !Sub '${VerificationCodeTable.Arn}'

  # Internal Queue
  InternalQueueName:
    Value: !GetAtt InternalQueue.Outputs.QueueName
    Description: pn-delivery-push actions queue name
  InternalQueueURL:
    Value: !GetAtt InternalQueue.Outputs.QueueURL
    Description: pn-delivery-push actions queue URL
  InternalQueueARN:
    Value: !GetAtt InternalQueue.Outputs.QueueARN
    Description: pn-delivery-push actions queue ARN
  InternalQueueAlarmARN:
    Value: !GetAtt InternalQueue.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push actions queue dlq alarm queue
  InternalQueueAgeAlarmARN:
    Value: !GetAtt InternalQueue.Outputs.SqsAgeAlarmArn
    Description: pn-delivery-push actions queue age alarm ARN