AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

Conditions:
  Never: !Equals [ 'true', 'false' ]

# dummy (null) resource, never created
Resources:
  # NotificationProgress DynamoDB Table for mock
  NotificationProgressTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-ExtChannels'
      AttributeDefinitions:
        - AttributeName: "iun"
          AttributeType: "S"
        - AttributeName: "destinationAddress"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun"
          KeyType: "HASH"
        - AttributeName: "destinationAddress"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Internal queues (creato nel modo standard per compatibilità stack del mock consolidatore)
  InternalQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      QueueName: "pn-external_channels_to_internal"
      VisibilityTimeout: 60
      DelaySeconds: 1

  # Mock ocr inputs
  MockOcrInputQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-mock_ocr_input'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1
  
  VerificationCodeTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-VerificationCode2'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  MockEcReceivedMessageTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-MockEcReceivedMessage'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "iunRecIndex"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        -
          IndexName: "iun-gsi"
          KeySchema:
            -
              AttributeName: "iunRecIndex"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true


Outputs:
  NotificationProgressDynamoTableName:
    Description: Name of dynamodb table containing Notification Progress for mock
    Value: !Ref NotificationProgressTable
  NotificationProgressDynamoTableArn:
    Description: ARN of dynamodb table containing Notification Progress for mock
    Value: !Sub '${NotificationProgressTable.Arn}'
  VerificationCodeTableDynamoTableName:
    Description: Name of dynamodb table containing verification code for mock
    Value: !Ref VerificationCodeTable
  VerificationCodeTableDynamoTableArn:
    Description: ARN of dynamodb table containing verification code for mock
    Value: !Sub '${VerificationCodeTable.Arn}'
  MockEcReceivedMessageTableDynamoTableName:
    Description: Name of dynamodb table containing requests
    Value: !Ref MockEcReceivedMessageTable
  MockEcReceivedMessageTableDynamoTableArn:
    Description: ARN of dynamodb table containing requests
    Value: !Sub '${MockEcReceivedMessageTable.Arn}'

  MockOcrInputQueueName:
    Value: !GetAtt MockOcrInputQueue.Outputs.QueueName
    Description: pn-external-channels mock ocr input queue name
  MockOcrInputQueueARN:
    Value: !GetAtt MockOcrInputQueue.Outputs.QueueARN
    Description: pn-external-channels mock ocr input queue ARN

  # Internal Queue
  InternalQueueURL:
    Description: "URL of new Amazon SQS Queue"
    Value:
      Ref: "InternalQueue"
  InternalQueueARN:
    Description: "ARN of new AmazonSQS Queue"
    Value:
      Fn::GetAtt:
        - "InternalQueue"
        - "Arn"
  InternalQueueName:
    Description: "Name of new Amazon SQS Queue"
    Value:
      Fn::GetAtt:
        - "InternalQueue"
        - "QueueName"